export enum UserRole {
  EVENT_CHEF = 'EVENT CHEF',
  KITCHEN_CHEF ='KITCHEN CHEF',
  SERVER = 'SERVER',
  CAPTAIN = 'CAPTAIN',
  SALES_PLANNER = 'SALES PLANNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
}