export enum UserRole {
  EVENT_CHEF = 'EVENT_CHEF',
  KITCHEN_CHEF ='KITCHEN_CHEF',
  SERVER = 'SERVER',
  CAPTAIN = 'CAPTAIN',
  SALES_PLANNER = 'SALES_PLANNER',
  ADMIN = 'ADMIN',
  MANAGER = 'MANAGER',
}